### ISSUE TITLE
Indice RT

### ISSUE THREAD

**Issue by Azzeccagarbugli** [MCilento93/ColoreRegioni#1]
Sarebbe interessante avere a disposizione anche i **valori RT** per monitorare più attentamente il rischio all'interno di ogni Regione come mostrato nel [sito del governo](http://www.salute.gov.it/portale/nuovocoronavirus/dettaglioContenutiNuovoCoronavirus.jsp?area=nuovoCoronavirus&id=5351&lingua=italiano&menu=vuoto). Non so quanto possa risultare complicato, ma sarebbe eventualmente un'aggiunta molto utile.

A quel punto le API potrebbero fornire le indicazione nel seguente modo: 
```
{
    "Marche" : [
         "color" : "arancione",
         "indexRT" : "1.07"
    ]
    ...
}
```

Cheers 👋

**Comment by MCilento93** [comment]
Ciao, Grazie per il suggerimento. Dal sito che mi hai linkato però non vedo il valore di Rt per le regioni. A dir la verità non ho visto in giro repo che lo mostravano. Calcolarlo secondo me non è banale, farci uno scraper potrebbe essere la strada più veloce. Dove hai visto l'Rt?

**Comment by Azzeccagarbugli** [comment]
Allora, qui ti link il file PDF
<http://www.salute.gov.it/imgs/C_17_monitoraggi_13_0_fileNazionale.pdf>
emanato dal Governo con cui all'interno ci sono tutti i valori *(era
raggiungibile dalla pagina che ti ho linkato nella issue)* e invece qui ti
linko un articolo del Resto del Carlino
<https://www.ilrestodelcarlino.it/cronaca/colori-regioni-oggi-1.5963173>
che spiega cosa sono e a cosa servono tali indici.

Credo che la soluzione possa essere, banalmente, analizzare i documenti
rilasciati e poi integrarlo nel software già presente.

Sono solo dei potenziali piccoli update, fammi sapere se ti può servire una
mano, così magari poi io aggiorno il sito di conseguenza dato che è da un
po' che non rilascio aggiornamenti!

Ciao!

Il giorno ven 29 gen 2021 alle ore 14:00 Mario Cilento <
notifications@github.com> ha scritto:

**Comment by Azzeccagarbugli** [comment]
Allora, qui ti [linko il file PDF emanato dal Governo](http://www.salute.gov.it/imgs/C_17_monitoraggi_13_0_fileNazionale.pdf) al cui interno ci sono tutti i valori e invece qui ti linko un [articolo del Resto del Carlino](https://www.ilrestodelcarlino.it/cronaca/colori-regioni-oggi-1.5963173) che spiega cosa sono e a cosa servono tali indici.

Credo che la soluzione possa essere, _banalmente_, analizzare i documenti rilasciati e poi integrarlo nel software già presente.

Si tratta di un potenziale piccolo update, fammi sapere se ti può servire una mano, così magari poi io aggiorno il [sito](https://checoloresono.info).

**Comment by MCilento93** [comment]
> Allora, qui ti [linko il file PDF emanato dal Governo](http://www.salute.gov.it/imgs/C_17_monitoraggi_13_0_fileNazionale.pdf) al cui interno ci sono tutti i valori e invece qui ti linko un [articolo del Resto del Carlino](https://www.ilrestodelcarlino.it/cronaca/colori-regioni-oggi-1.5963173) che spiega cosa sono e a cosa servono tali indici.
> 
> Credo che la soluzione possa essere, _banalmente_, analizzare i documenti rilasciati e poi integrarlo nel software già presente.
> 
> Si tratta di un potenziale piccolo update, fammi sapere se ti può servire una mano, così magari poi io aggiorno il [sito](https://checoloresono.info).

Grazie @Azzeccagarbugli per i link.
Abbiamo avuto modo di visualizzare i pdf a cui fai riferimento e ragionare un po' sugli indici Rt.

Le conclusioni a cui siamo arrivate sono:
1. per ora non abbiamo intenzione di sviluppare il calcolo dell'indice Rt perchè le formulazioni non sono univoche e rischieremo di sviluppare con i dati raccolti in [italy_coviddata](https://github.com/MCilento93/italy_coviddata) dei risultati diversi da quelli sul sito del governo. 
2. Lo scraping dei pdf è fattibile ma richide dependencies piuttosto spinte che non riesco a rendere compatibili con i server hostanti il [progetto principale](https://github.com/MCilento93/italy_coviddata).

Ma non è un rifiuto categorico, sto cercando in giro su github un approccio più fattibile per la cosa. Tuttavia siamo più interessati a sviluppare qualcosa sui vaccini piuttosto che sul calcolo dell'indice Rt.

Mario & [@giu67890](https://github.com/giu67890)

**Comment by MCilento93** [comment]
Ciao
ho trovato questo sulla mia home.
Consiglio di darci [un'occhiata :D](https://github.com/CloudItaly/Indice-RT)
