### ISSUE TITLE
Dati storici colore regione 

### ISSUE THREAD

**Issue by SamueleVianello** [MCilento93/ColoreRegioni#2]
Ciao Mario,
mi chiedevo se per caso conosci delle risorse da cui posso ottenere i dati storici del colore delle regioni (data, regione, colore, idealmente in csv ma altro formato testo va bene). Ho provato a vedere nelle repo ufficiali https://github.com/pcm-dpc/COVID-19 ma non sono riuscito a trovare uno storico.

Sto provando a fare una mini dashboard su google sheet che mi permetta di vedere l'andamento dei casi e confrontarlo con il relativo colore della regione per vedere quant'è l'impatto delle restrizioni.

Grazie in anticipo,
Samuele

**Comment by MCilento93** [comment]
Ciao Samuele, 
grazie per aver aperto il topic.

Purtroppo neanche io ho mai avuto lo storico dei dati sul colore delle regioni e/o pensato di integrarlo ai dati sul contaglio che hai postato per il progetto [italy_coviddata](https://github.com/MCilento93/italy_coviddata).

L'analisi da mostrare in dashboard mi sembra un'ottima idea tuttavia non saprei come reperire i dati vecchi. 
Ovviamente si può scrivere una routine daily con [ColoreRegioni](https://github.com/MCilento93/ColoreRegioni) per aggionare un contatore su qualche db, ma non è stato implementato da me. Mi dispiace 😞
