### ISSUE TITLE
Zona bianca

### ISSUE THREAD

**Issue by Azzeccagarbugli** [MCilento93/ColoreRegioni#3]
Come da nuovo decreto, e l'avvento delle **zone bianche** sarebbe necessario l'update dello scraper. 

Ho appena notato che il JSON restituisce il seguente oggetto per la Sardegna ad esempio:

```
Sardegna": [
    
  ],
```

Grazie mille!

**Comment by MCilento93** [comment]
Si,
avevo preventivato una situazione del genere.
Mesi fa quando non si sapeva cosa ci fosse prima della zona gialla immaginai si parlasse di zona verde.

Correggo e riuppo su Pypi il codice, tra oggi e domani purtroppo, sono occupato.

**Comment by MCilento93** [comment]
Ho aggiornato il repo (funziona ora per le regioni bianche).
Sto caricando su Pypi la versione aggiornata, ma allucinante ho un gateway error ... quindi per oggi mi dispiace ma non credo di fixare la cosa. Leggendo gli stackoverflow su twin vedo soluzioni poco pratiche.
Ti faccio sapere,
![image](https://user-images.githubusercontent.com/66259011/109539177-4df34f00-7ac1-11eb-8138-b1db5ca77ece.png)

**Comment by Azzeccagarbugli** [comment]
Perfetto, tienimi aggiornato e grazie mille!

**Comment by MCilento93** [comment]
Caro,
fixato.

Scarica pure il nuovo pacchetto su pypi alla versione 0.2.0

`pip install ColoreRegioni==0.2.0`
